services:
  apache:
    image: php:8.4-apache
    container_name: lib-backend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    build:
      context: .
      args:
        HOST_UID: 1001
        HOST_GID: 1001
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
